### ISSUE TITLE
Rethinking exprhead

### ISSUE THREAD

**Issue by willow-ahrens** [JuliaSymbolics/TermInterface.jl#10]
Not all usages of rewriting are for julia-esque programs, so its not immediately clear what `exprhead` should be for those applications, and the documentation doesn't make it super clear. Can we make `exprhead` default to `:call` so that the `operation` function defaults to being understood as returning a relevant expression node constructor by default?

**Comment by peterahrens** [comment]
Much of the Symbolics ecosystem don't really even work correctly if the "operation" is an expression itself, so specializing for cases like `:ref` is somewhat esoteric (at least as I use TermInterface). Perhaps there's a way to make `exprhead` a function that sometimes gets called on the result of `operation`. Or at least could we make `exprhead` an optional overload instead of a required interface component? I appreciated TermInterface for its simplicity, and adding a function like this forces me to decide whether my mathematical objects I'm rewriting are semantically closer to a julia function call or a julia :ref operator, which feels like an unrelated distinction.

**Comment by shashi** [comment]
I agree that `exprhead` made things awkward.

**Comment by shashi** [comment]
And yeah it should probably be a property of the term representation type, if we still had `similarterm` take an instance as the first argument (rather than the type), you'd be able to get the exprhead when a term type needs it.

Another possible solution is have `operation(x)` return something like `Syntax(:ref)` when it's not representing a function call.

**Comment by shashi** [comment]
And that won't break any existing code SymbolicUtils and above because `operation` does not even make sense anyway when exprhead is not `:call`

**Comment by peterahrens** [comment]
This is related to a programming pattern I've seen in rewriting systems. Users want to add metadata about the expression node, but don't want to put it in the arguments because associativity/commutativity properties aren't generic enough to understand not to mess with the metadata, and the operation field isn't generic enough to hold the metadata.

I usually choose to use nodes like `Call` or `Ref`, and put the array to be referenced or function to be called in the args field (similar to how it's handled by Julia's `Expr` type), and handle associativity or commutivity myself.

If you expand the functionality of the operation field enough, it starts to look like just another argument. I think that allowing the operation to be an object in `similarterm` is a good compromise here. This comment was a very long way of  agreeing with you.

**Comment by peterahrens** [comment]
Bumping this issue since it's still unresolved. Should I just maintain a fork of SymbolicUtils 0.17.0?

**Comment by peterahrens** [comment]
I can file a PR reverting similarterm to the old interface; I suspect that would be a big change, is that correct?

**Comment by 0x0f0f0f** [comment]
> Much of the Symbolics ecosystem don't really even work correctly if the "operation" is an expression itself, so specializing for cases like `:ref` is somewhat esoteric (at least as I use TermInterface). Perhaps there's a way to make `exprhead` a function that sometimes gets called on the result of `operation`. Or at least could we make `exprhead` an optional overload instead of a required interface component? I appreciated TermInterface for its simplicity, and adding a function like this forces me to decide whether my mathematical objects I'm rewriting are semantically closer to a julia function call or a julia :ref operator, which feels like a choice I shouldn't have to make.

Probably a good idea to default `exprhead` to be `:call`

**Comment by 0x0f0f0f** [comment]
There's the case where you want to manipulate Julia code or Symbolics objects at the same time. If we defined `operation(x::Expr) = x.head # :call`, then all the support for Julia exprs breaks. 

See 
https://github.com/JuliaSymbolics/TermInterface.jl/blob/master/src/expr.jl

for more details

This is also useful for codegen.

We could try removing `exprhead` but leaving

```
operation(e::Expr) = expr_operation(e, Val{exprhead(e)}())
arguments(e::Expr) = expr_arguments(e, Val{exprhead(e)}())

# See https://docs.julialang.org/en/v1/devdocs/ast/
expr_operation(e::Expr, ::Union{Val{:call},Val{:macrocall}}) = e.args[1]
expr_operation(e::Expr, ::Union{Val{:ref}}) = getindex
expr_operation(e::Expr, ::Val{T}) where {T} = T
```

As is
