### ISSUE TITLE
`istree` on Expr

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/TermInterface.jl#6]
should not be true in my opinion because terms may want to hold `Expr`s.  As we discussed, MT could use `_istree(x) = istree(x) || x isa Expr`...

cc @0x0f0f0f

**Comment by 0x0f0f0f** [comment]
I think that this issue generalizes to a broader scope. For example, I've encountered a similar problem when fixing a metatheory.jl test case regarding rewriting categorical expressions. I wanted to skip the walk of nodes with a certain specific `operation` using Rewriters.Postwalk (this can be reduced/converted intuitively to the case of an `istree(::T) type), treating those nodes like terminals but only in a certain moment and scope. I still wanted to treat those nodes as trees during other tasks. Maybe a finer degree of control over `istree` is needed. Wrapping all the MT calls to TermInterface.isexpr seems like a bad hardcoding choice, because if you want to rewrite Symbolics expressions that hold `Expr`s as non-tree terminals MT would still treat them as trees without any degree of control. Lets chat about potential solutions that are not orthogonal to either packages design. I'm sure there is one that is compatible with both SU being specific on types and MT being as general as possible

cc @ChrisRackauckas and @philzook58 s for any suggestions

**Comment by 0x0f0f0f** [comment]
I would close this since the integration worked out well
